config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root 'posts#index'
  resources :posts do
    post 'like', to: 'posts#like', as: :like, on: :member
  end
  
  resources :users, only:[:show] do
    post 'follow', to: 'users#follow', as: :follow, on: :member
  end
  
  # resources :posts do
  #   resources :comments
  # end
  
  # get 'mypage', to: 'posts#mypage'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
    mount_uploader :image, ImageUploader
    
    # content에 validates를 하는데 true이면 무조건 값이 들어가야 된다는 뜻
    validates :image, presence: true
    validates :content, presence: true
    validates :user_id, presence: true
    
    belongs_to :user
    
    has_many :likes
    has_many :like_users, through: :likes, source: :user
    
    # @post.toggle_like(current_user)
    def toggle_like(user)
        if self.like_users.include?(user)
            self.like_users.delete(user)
        else
            self.like_users.push(user)
            # self.like_users<<user
        end
    end
    
    # @post.activate!
    # def activate!
    #     self.active = false
    #     self.save
    # end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :like]
  before_action :authenticate_user! #, except:[:index, :show]
  # before_action :check_user, only: [:edit, :update, :destroy]
  load_and_authorize_resource
  
  # GET /posts
  # GET /posts.json
  def index
    # 검색창 관련
    if params.has_key?(:content)
     @posts = Post.where('content like ?' , "%#{params[:content]}%")
    else
     @posts = Post.where(user_id: current_user.followers.ids.push(current_user.id))
    end
    # unless (current_user == nil) 
    #   @posts = Post.where(user_id: current_user.followees.ids.push(current_user.id))
    # else 
    #   @posts = Post.all
    # end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.new(post_params)
    # @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def mypage
    @posts = current_user.posts
  end
  
  # POST 'posts/:id/like'
  def like
    @post.toggle_like(current_user)
    redirect_back(fallback_location: root_path)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:image, :content)
    end
    
    # def check_user
    #   redirect_to root_path, notice: "권한이 없습니다." and return unless @post.user == current_user
    # end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :image %>
    <!--accept: "image/*" : image의 어떤 확장자가 와도 업로드 가능-->
    <%= form.file_field :image, accept: "image/*"  %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, required: true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<!--검색창-->
<%= form_tag posts_path, method: :get do %>
  Content:
  <%= text_field_tag :content, params[:content] %>
  <%= submit_tag :search %>
<% end %>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>User</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= image_tag post.image.url(:thumb) %></td>
        <td><%= link_to post.user.name, post.user %></td>
        <td><%= post.content %></td>
        <td><%= link_to 'Show', post %></td>
        <% if can? :manage, post %>
          <td><%= link_to 'Edit', edit_post_path(post) %></td>
          <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/mypage.html.erb
<p id="notice"><%= notice %></p>

<h1>My Page</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>User</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= image_tag post.image.url(:thumb) %></td>
        <td><%= post.user.name %></td>
        <td><%= post.content %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Edit User', edit_user_registration_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <!--<img src="<%#= @post.image.url %>"></img>-->
  <%= image_tag @post.image.url %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user.name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<p>
  <% if @post.like_users.include?(current_user) %>
    <%= link_to 'Unlike', like_post_path, method: :post %>
  <% else %>
    <%= link_to 'Like', like_post_path, method: :post %>
  <% end %>
</p>

<p>
  <strong>Like:</strong>
  <%= @post.like_users.count %>
</p>

<% if can? :manage, @post %>
  <%= link_to 'Edit', edit_post_path(@post) %> |
<% end %>
<%= link_to 'Back', posts_path %>